import { and, desc, eq, isNull, sql } from 'drizzle-orm';
import { db } from '@/db/client';
import { clinics, subscriptions, subscriptionWebhookEvents } from '@/db/schema';
import type { NewSubscription, Subscription } from '@/db/schema';

export async function getSubscription(clinicId: string): Promise<Subscription | null> { const [row] = await db.select().from(subscriptions).where(and(eq(subscriptions.clinicId, clinicId), isNull(subscriptions.deletedAt))).limit(1); return row ?? null; }
export async function upsertSubscription(clinicId: string, patch: Omit<NewSubscription, 'clinicId'>): Promise<Subscription> { const current = await getSubscription(clinicId); if (current) { const [row] = await db.update(subscriptions).set({ ...patch, updatedAt: new Date() }).where(and(eq(subscriptions.clinicId, clinicId), isNull(subscriptions.deletedAt))).returning(); return row; } const [row] = await db.insert(subscriptions).values({ ...patch, clinicId }).returning(); return row; }
export async function updateSubscription(clinicId: string, patch: Partial<Omit<NewSubscription, 'clinicId'>>): Promise<Subscription | null> { const [row] = await db.update(subscriptions).set({ ...patch, updatedAt: new Date() }).where(and(eq(subscriptions.clinicId, clinicId), isNull(subscriptions.deletedAt))).returning(); return row ?? null; }
export async function getSubscriptionByCashfreeId(clinicId: string, cashfreeSubscriptionId: string): Promise<Subscription | null> { const [row] = await db.select().from(subscriptions).where(and(eq(subscriptions.clinicId, clinicId), eq(subscriptions.cashfreeSubscriptionId, cashfreeSubscriptionId), isNull(subscriptions.deletedAt))).limit(1); return row ?? null; }
export async function updateClinicStatus(clinicId: string, status: 'active' | 'past_due' | 'suspended' | 'canceled'): Promise<void> { await db.update(clinics).set({ status, updatedAt: new Date() }).where(eq(clinics.id, clinicId)); }
export async function insertWebhookEvent(clinicId: string, eventId: string, payload: object, status: string): Promise<boolean> { try { await db.insert(subscriptionWebhookEvents).values({ eventId, payload, status }); return true; } catch (error) { if (typeof error === 'object' && error !== null && (error as { code?: string }).code === '23505') return false; throw error; } }
export async function listWebhookEvents(clinicId: string) { return db.select({ eventId: subscriptionWebhookEvents.eventId, status: subscriptionWebhookEvents.status, processedAt: subscriptionWebhookEvents.processedAt }).from(subscriptionWebhookEvents).innerJoin(subscriptions, sql`${subscriptions.cashfreeSubscriptionId} = ${subscriptionWebhookEvents.payload}->>'subscription_id'`).where(and(eq(subscriptions.clinicId, clinicId), isNull(subscriptions.deletedAt))).orderBy(desc(subscriptionWebhookEvents.processedAt)); }
